// @index('./*', f => `export * from '${f.path}'`)
export * from './BorderProps';
export * from './BorderScale';
export * from './ColSize';
export * from './Display';
export * from './DisplayProps';
export * from './DivElement';
export * from './FlexboxProps';
export * from './GridProps';
export * from './OneZero';
export * from './PaletteColor';
export * from './PaletteProps';
export * from './Position';
export * from './PositionsProps';
export * from './ShadowsProps';
export * from './SizingProps';
export * from './SpacingProps';
export * from './SpacingScale';
export * from './TypographyProps';
